use_default_settings:
  engines:
    keep_only:
      - yahoo
      - duckduckgo

server:
  secret_key: "change-me-to-a-random-string"
  limiter: false
  image_proxy: false
  port: 8080
  bind_address: "0.0.0.0"

search:
  safe_search: 1
  autocomplete: ""
  default_lang: "zh-CN"
  formats:
    - html
    - json

ui:
  static_use_hash: true

outgoing:
  request_timeout: 5.0
  max_request_timeout: 10.0

engines:
  - name: yahoo
    disabled: false
